// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegistryBridge.Api.Data;

#nullable disable

namespace RegistryBridge.Api.Migrations
{
    [DbContext(typeof(RegistryBridgeDbContext))]
    [Migration("20260915065205_AddRunLogTruncation")]
    partial class AddRunLogTruncation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegistryBridge.Api.Catalog.CatalogRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("catalog_revisions", (string)null);
                });

            modelBuilder.Entity("RegistryBridge.Api.Catalog.CatalogState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRevisionId");

                    b.ToTable("catalog_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.ArtifactOutcomeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SynchronizationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SynchronizationRunId", "Order")
                        .IsUnique();

                    b.ToTable("artifact_outcomes", (string)null);
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.RunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SynchronizationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SynchronizationRunId", "OccurredAt");

                    b.ToTable("run_logs", (string)null);
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.SynchronizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CatalogRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LogsTruncated")
                        .HasColumnType("boolean");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogRevisionId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("synchronization_runs", (string)null);
                });

            modelBuilder.Entity("RegistryBridge.Api.Catalog.CatalogState", b =>
                {
                    b.HasOne("RegistryBridge.Api.Catalog.CatalogRevision", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentRevision");
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.ArtifactOutcomeRecord", b =>
                {
                    b.HasOne("RegistryBridge.Api.SynchronizationRuns.SynchronizationRun", "SynchronizationRun")
                        .WithMany("Outcomes")
                        .HasForeignKey("SynchronizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SynchronizationRun");
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.RunLog", b =>
                {
                    b.HasOne("RegistryBridge.Api.SynchronizationRuns.SynchronizationRun", "SynchronizationRun")
                        .WithMany("Logs")
                        .HasForeignKey("SynchronizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SynchronizationRun");
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.SynchronizationRun", b =>
                {
                    b.HasOne("RegistryBridge.Api.Catalog.CatalogRevision", "CatalogRevision")
                        .WithMany()
                        .HasForeignKey("CatalogRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CatalogRevision");
                });

            modelBuilder.Entity("RegistryBridge.Api.SynchronizationRuns.SynchronizationRun", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Outcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
